# -*- coding: utf-8 -*-
"""Student Performance Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssopUrvkmiyrTamys7F4R066j-0VtRPb
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Apply Seaborn theme safely
sns.set_theme(style="whitegrid")  # Clean, attractive theme

# Load dataset
df = pd.read_csv('/content/student_data.csv')

# Calculate average score using G1, G2, G3
df['Average Score'] = df[['G1', 'G2', 'G3']].mean(axis=1)

# Identify top-performing student
average_scores = df['Average Score'].to_numpy()
top_index = np.argmax(average_scores)
top_score = average_scores[top_index]

# Subject averages for Pie Chart
subject_averages = df[['G1', 'G2', 'G3']].mean()

# Set up the dashboard layout - Horizontal Panels
fig, axs = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle('📊 Student Performance Dashboard', fontsize=18, fontweight='bold')

# Grouped Bar Chart
x = np.arange(len(df))
width = 0.25
axs[0].bar(x - width, df['G1'], width, label='G1')
axs[0].bar(x, df['G2'], width, label='G2')
axs[0].bar(x + width, df['G3'], width, label='G3')
axs[0].set_title('Scores Across Periods', fontsize=14)
axs[0].set_xlabel('Student Index')
axs[0].set_ylabel('Scores')
axs[0].legend()
axs[0].tick_params(axis='x', labelrotation=45)

# Pie Chart
axs[1].pie(subject_averages, labels=['G1', 'G2', 'G3'], autopct='%1.1f%%', startangle=140)
axs[1].set_title('Average Scores by Grade Period', fontsize=14)

# Scatter Chart
scatter = axs[2].scatter(df['absences'], df['Average Score'], c=df['Average Score'], cmap='viridis', edgecolor='black')
axs[2].set_title('Absences vs Average Score', fontsize=14)
axs[2].set_xlabel('Absences')
axs[2].set_ylabel('Average Score')
axs[2].grid(True)

# Add color bar to scatter chart
cbar = fig.colorbar(scatter, ax=axs[2])
cbar.set_label('Average Score')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# Summary
summary = f"""
Summary of Findings:
- 🎓 Top-performing student is at index {top_index} with an average score of {top_score:.2f}.
- 📊 Average Scores:
  - G1: {subject_averages['G1']:.2f}
  - G2: {subject_averages['G2']:.2f}
  - G3: {subject_averages['G3']:.2f}
- 📈 Grouped bar chart reveals overall score progression.
- 🥧 Pie chart shows how scores are balanced across periods.
- 📉 Scatter plot suggests higher absences usually relate to lower average scores.
"""
print(summary)